// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALmGpGUOyjgf9E5Ph4RCJak2XwgkCmJ3c',
    appId: '1:331802698520:web:da52dc837f01d58ceb746d',
    messagingSenderId: '331802698520',
    projectId: 'cognifit-fcm',
    authDomain: 'cognifit-fcm.firebaseapp.com',
    storageBucket: 'cognifit-fcm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx5qG-K7viMM_iIPLbHE7vlO6eLxqK_mQ',
    appId: '1:331802698520:android:de5e152eade1bccceb746d',
    messagingSenderId: '331802698520',
    projectId: 'cognifit-fcm',
    storageBucket: 'cognifit-fcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPGALjquk3HtPt1cSIT-8vn-tB_M1FbBY',
    appId: '1:331802698520:ios:f36fd8c98d42e415eb746d',
    messagingSenderId: '331802698520',
    projectId: 'cognifit-fcm',
    storageBucket: 'cognifit-fcm.firebasestorage.app',
    iosBundleId: 'com.example.cognifit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPGALjquk3HtPt1cSIT-8vn-tB_M1FbBY',
    appId: '1:331802698520:ios:f36fd8c98d42e415eb746d',
    messagingSenderId: '331802698520',
    projectId: 'cognifit-fcm',
    storageBucket: 'cognifit-fcm.firebasestorage.app',
    iosBundleId: 'com.example.cognifit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALmGpGUOyjgf9E5Ph4RCJak2XwgkCmJ3c',
    appId: '1:331802698520:web:514c4f69ad5a0b3eeb746d',
    messagingSenderId: '331802698520',
    projectId: 'cognifit-fcm',
    authDomain: 'cognifit-fcm.firebaseapp.com',
    storageBucket: 'cognifit-fcm.firebasestorage.app',
  );
}
